spring.datasource.url=jdbc:postgresql://localhost:5432/vexa
spring.datasource.username=postgres
spring.datasource.password=postgres

logging.level.org.flywaydb=DEBUG

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=RPYT3IFzoTqB5zv7n6g0Fv6zmVVcsd1SxHKQDufUzFz
jwt.expiration=28800000
